---
- name: Install by YUM | Ensure clickhouse repo GPG key imported
  rpm_key:
    state: present
    key: "{{ clickhouse_repo_key }}"
  tags: [install]
  become: true

- name: Install by YUM | Ensure clickhouse repo installed
  yum_repository:
    name: clickhouse
    file: clickhouse
    description: "Clickhouse repo"
    baseurl: "{{ clickhouse_repo }}"
    enabled: yes
    gpgcheck: 1
    gpgkey: "{{ clickhouse_repo_key }}"
  tags: [install]
  become: true

- name: Check if clickhouse is installed
  command: rpm -q {{ item }}
  register: clickhouse_check
  ignore_errors: true
  changed_when: false
  with_items: "{{ clickhouse_package }}"
  tags: [install]

- name: Install by YUM | Install clickhouse package (latest)
  command: dnf install -y {{ clickhouse_package | join(' ') }}
  become: true
  when: 
    - clickhouse_version == 'latest'
    - clickhouse_check.results | map(attribute='rc') | select('eq', 1) | list | length > 0
  tags: [install]

- name: Install by YUM | Install clickhouse package (specific version)
  command: dnf install -y {{ clickhouse_package | map('regex_replace', '$', '-' + clickhouse_version) | join(' ') }}
  become: true
  when: 
    - clickhouse_version != 'latest'
    - clickhouse_check.results | map(attribute='rc') | select('eq', 1) | list | length > 0
  tags: [install]
